# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-test-deploy:
    docker:
      - image: "cimg/node:16.15.0"
    steps:
      - checkout
      - run: echo "Build started on `date`"
      - run: yarn install && yarn build
      - run: echo "Test started on `date`"
      - add_ssh_keys:
          fingerprints:
            - "ad:41:49:c3:e5:ea:f9:a2:74:ac:dc:f7:1f:9f:8d:ae"
      - deploy:
          name: Deploy next js app
          command: |
            git config --global user.name "dievasetyatama"
            git config --global user.email "dieva@fivejack.com"
      - run: echo "Deploy started on `date`"
      - run: yarn deploy
workflows:
  build-branch-beta:
    jobs:
      - need-approval:
          type: approval
          filters:
            branches:
              only:
                - beta
      - build-test-deploy:
          requires:
            - need-approval
