# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    docker:
      - image: "cimg/node:16.15.0"
    steps:
      - checkout
      - run: echo "Build started on `date`"
      - run: yarn install && yarn build
      - run: echo "Test started on `date`"
      - run: yarn test
      - persist_to_workspace:
          root: public
          paths:
            - "*"
  deploy:
    docker:
      - image: cimg/node:16.15.0
    steps:
      - checkout
      - attach_workspace:
          at: public
      - add_ssh_keys:
          fingerprints:
            - "1d:0c:ea:28:8a:4f:f0:5d:98:e1:ca:93:0f:38:d6:ab"
      - deploy:
          name: Deploy website
          command: |
            git config --global user.name "Dieva S"
            git config --global user.email "dieva@fivejack.com"
            sh deploy.sh
workflows:
  build-branch-beta:
    jobs:
      - need-approval:
          type: approval
          filters:
            branches:
              only:
                - beta
      - build-and-test:
          requires:
            - need-approval
      - deploy:
          requires:
            - build-and-test
