# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-test:
    docker:
      - image: "cimg/node:16.15.0"
    steps:
      - run: echo "Build started on `date`"
      - run: yarn install && yarn build
      - run: echo "Test started on `date`"
      - run: yarn test
    entrypoint:
      - run: yarn start
workflows:
  build-branch-beta:
    jobs:
      - need_approval:
          type: approval
          filters:
            branches:
              only:
                - beta
      - build-and-test:
          requires:
            - need_approval
